services:
  - type: web
    name: nykaa-product-advisor
    env: python
    buildCommand: |
      sudo apt install chromium-browser chromium-driver
      pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: CHROME_BIN  
        value: /usr/bin/chromium
