services:
  - type: web
    name: nykaa-product-advisor
    env: python
    buildCommand: |
      # Update package lists
      apt-get update
      # Install Firefox and GeckoDriver
      apt-get install -y firefox-esr
      wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
      tar -xzf geckodriver-v0.33.0-linux64.tar.gz
      chmod +x geckodriver
      mv geckodriver /usr/local/bin/
      pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FIREFOX_BIN
        value: /usr/bin/firefox-esr
      - key: GECKODRIVER_PATH
        value: /usr/local/bin/geckodriver